# Generated by Django 5.0.6 on 2024-06-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
